<template>
  <div class="receipt-list-container">
    <h2 style="text-align: center">Recent Receipts</h2>

    <div v-if="loading" class="loading">Loading receipts...</div>

    <div v-else-if="receiptStore.receipts.length === 0" class="empty-state">
      <FileTextIcon :size="64" class="empty-icon" />
      <p>No receipts yet</p>
      <p class="empty-subtext">Create your first receipt to get started</p>
    </div>

    <div v-else class="receipts-grid">
      <div
        v-for="receipt in receiptStore.receipts"
        :key="receipt.receiptNumber"
        class="receipt-card"
      >
        <div class="receipt-card-header">
          <h3>{{ receipt.receiptNumber }}</h3>
          <span class="receipt-date">{{ formatDate(receipt.date) }}</span>
        </div>

        <div class="receipt-card-body">
          <p class="customer-name">{{ receipt.customer.name }}</p>
          <p class="receipt-total">{{ formatCurrency(receipt.total) }}</p>
          <p class="items-count">{{ receipt.items.length }} item(s)</p>
        </div>

        <div class="receipt-card-actions">
          <button @click="viewReceipt(receipt)" class="btn-view">View</button>
          <button @click="downloadReceipt(receipt)" class="btn-download-small">
            <DownloadIcon :size="16" />
          </button>
          <button @click="deleteReceipt(receipt.receiptNumber)" class="btn-delete">
            <Trash2Icon :size="16" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import {
  FileText as FileTextIcon,
  Download as DownloadIcon,
  Trash2 as Trash2Icon,
} from 'lucide-vue-next'
import { useReceiptStore } from '../stores/receiptStore'
import jsPDF from 'jspdf'

const receiptStore = useReceiptStore()
const loading = ref(true)

onMounted(async () => {
  await receiptStore.loadReceipts()
  loading.value = false
})

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

const formatCurrency = (amount) => {
  return `₦${amount.toLocaleString('en-NG')}`
}

const viewReceipt = (receipt) => {
  alert(`Viewing receipt: ${receipt.receiptNumber}`)
}

// ✅ Generate clean, “PAID” receipt PDF
const downloadReceipt = (receipt) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a5' })

  const logo = new Image()
  logo.src = '/logo.png' // place in public/

  logo.onload = () => {
    // Header with logo + store info
    doc.addImage(logo, 'PNG', 10, 10, 25, 25)
    doc.setFontSize(15)
    doc.text('CONPAY', 40, 18)
    doc.setFontSize(9)
    doc.text('Gadget Sales & Accessories', 40, 23)
    doc.text('Email: conpay@gadgets.ng | +234 812 345 6789', 40, 28)
    doc.line(10, 35, 140, 35)

    // Receipt info
    doc.setFontSize(12)
    doc.text('RECEIPT', 10, 42)
    doc.setFontSize(9)
    doc.text(`Receipt #: ${receipt.receiptNumber}`, 10, 48)
    doc.text(`Date: ${formatDate(receipt.date)}`, 10, 53)

    // Customer info
    doc.text(`Customer: ${receipt.customer.name}`, 10, 63)
    if (receipt.customer.email) doc.text(`Email: ${receipt.customer.email}`, 10, 68)
    if (receipt.customer.phone) doc.text(`Phone: ${receipt.customer.phone}`, 10, 73)

    // Items
    let y = 85
    doc.setFontSize(10)
    doc.text('Items', 10, y)
    y += 5
    receipt.items.forEach((item, i) => {
      doc.text(`${i + 1}. ${item.name}`, 12, y)
      doc.text(`x${item.quantity}`, 90, y)
      doc.text(formatCurrency(item.price * item.quantity), 125, y, { align: 'right' })
      y += 6
    })

    // Totals
    y += 6
    doc.line(10, y, 140, y)
    y += 6
    doc.text(`Subtotal: ${formatCurrency(receipt.subtotal)}`, 90, y)
    y += 5
    doc.text(`Tax: ${formatCurrency(receipt.tax)}`, 90, y)
    y += 5
    doc.setFont(undefined, 'bold')
    doc.text(`Total: ${formatCurrency(receipt.total)}`, 90, y)
    doc.setFont(undefined, 'normal')

    // PAID watermark
    doc.setTextColor(255, 0, 0)
    doc.setFontSize(30)
    doc.text('PAID', 75, 130, { align: 'center', angle: 25 })
    doc.setTextColor(0, 0, 0)

    // Footer
    doc.setFontSize(8)
    doc.text('Thank you for your purchase!', 75, 145, { align: 'center' })
    doc.text('Generated by Conpay Receipt System', 75, 150, { align: 'center' })

    doc.save(`${receipt.receiptNumber}.pdf`)
  }
}

const deleteReceipt = async (receiptNumber) => {
  if (confirm(`Are you sure you want to delete receipt ${receiptNumber}?`)) {
    await receiptStore.deleteReceipt(receiptNumber)
  }
}
</script>

<style scoped>
.receipt-list-container {
  margin-top: 3rem;
}

.receipt-list-container h2 {
  font-size: 1.8rem;
  color: #1a202c;
  margin-bottom: 1.5rem;
}

.loading {
  text-align: center;
  padding: 3rem;
  color: #718096;
}

.empty-state {
  text-align: center;
  padding: 4rem 2rem;
  color: #718096;
}

.empty-icon {
  color: #cbd5e0;
  margin-bottom: 1rem;
}

.empty-state p {
  margin: 0.5rem 0;
  font-size: 1.2rem;
}

.empty-subtext {
  font-size: 1rem;
  color: #a0aec0;
}

.receipts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1.5rem;
}

.receipt-card {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  transition:
    transform 0.2s,
    box-shadow 0.2s;
}

.receipt-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.receipt-card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid #e2e8f0;
}

.receipt-card-header h3 {
  color: #667eea;
  margin: 0;
  font-size: 1.1rem;
}

.receipt-date {
  color: #718096;
  font-size: 0.9rem;
}

.receipt-card-body {
  margin-bottom: 1rem;
}

.customer-name {
  font-weight: 600;
  color: #1a202c;
  margin: 0 0 0.5rem 0;
}

.receipt-total {
  font-size: 1.5rem;
  font-weight: 700;
  color: #667eea;
  margin: 0.5rem 0;
}

.items-count {
  color: #718096;
  font-size: 0.9rem;
  margin: 0;
}

.receipt-card-actions {
  display: flex;
  gap: 0.5rem;
}

.btn-view {
  flex: 1;
  background: #667eea;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
}

.btn-view:hover {
  background: #5a67d8;
}

.btn-download-small,
.btn-delete {
  background: #e2e8f0;
  border: none;
  padding: 0.5rem;
  border-radius: 6px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-download-small:hover {
  background: #cbd5e0;
}

.btn-delete {
  background: #fed7d7;
}

.btn-delete:hover {
  background: #fc8181;
  color: white;
}
</style>
