<template>
  <div class="invoice-list-container">
    <h2>Recent Invoices</h2>

    <div v-if="loading" class="loading">Loading invoices...</div>

    <div v-else-if="invoiceStore.invoices.length === 0" class="empty-state">
      <FileTextIcon :size="64" class="empty-icon" />
      <p>No invoices yet</p>
      <p class="empty-subtext">Create your first invoice to get started</p>
    </div>

    <div v-else class="invoices-grid">
      <div
        v-for="invoice in invoiceStore.invoices"
        :key="invoice.invoiceNumber"
        class="invoice-card"
      >
        <div class="invoice-card-header">
          <h3>{{ invoice.invoiceNumber }}</h3>
          <span class="invoice-date">{{ formatDate(invoice.date) }}</span>
        </div>

        <div class="invoice-card-body">
          <p class="customer-name">{{ invoice.customer.name }}</p>
          <p class="invoice-total">{{ formatCurrency(invoice.total) }}</p>
          <p class="items-count">{{ invoice.items.length }} item(s)</p>
        </div>

        <div class="invoice-card-actions">
          <button @click="viewInvoice(invoice)" class="btn-view">View</button>
          <button @click="downloadInvoice(invoice)" class="btn-download-small">
            <DownloadIcon :size="16" />
          </button>
          <button @click="deleteInvoice(invoice.invoiceNumber)" class="btn-delete">
            <Trash2Icon :size="16" />
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import {
  FileText as FileTextIcon,
  Download as DownloadIcon,
  Trash2 as Trash2Icon,
} from 'lucide-vue-next'
import { useInvoiceStore } from '../stores/invoiceStore'
import jsPDF from 'jspdf'

const invoiceStore = useInvoiceStore()
const loading = ref(true)

onMounted(async () => {
  await invoiceStore.loadInvoices()
  loading.value = false
})

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-NG', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  })
}

const formatCurrency = (amount) => {
  return `₦${amount.toLocaleString('en-NG')}`
}

const viewInvoice = (invoice) => {
  alert(`Viewing invoice: ${invoice.invoiceNumber}`)
}

// ✅ Generate clean PDF with logo and "PAID" watermark
const downloadInvoice = (invoice) => {
  const doc = new jsPDF({ unit: 'mm', format: 'a5' }) // smaller, receipt-like size

  const logo = new Image()
  logo.src = '/logo.png' // stored in /public/logo.png

  logo.onload = () => {
    // Add logo and header
    doc.addImage(logo, 'PNG', 10, 10, 25, 25)
    doc.setFontSize(16)
    doc.text('CONPAY', 40, 18)
    doc.setFontSize(9)
    doc.text('Gadget Sales & Accessories', 40, 23)
    doc.text('Email: conpay@gadgets.ng | +234 812 345 6789', 40, 28)

    // Divider
    doc.line(10, 35, 140, 35)

    // Invoice title and metadata
    doc.setFontSize(12)
    doc.text('INVOICE', 10, 42)
    doc.setFontSize(9)
    doc.text(`Invoice #: ${invoice.invoiceNumber}`, 10, 48)
    doc.text(`Date: ${formatDate(invoice.date)}`, 10, 53)

    // Customer info
    doc.text(`Billed To: ${invoice.customer.name}`, 10, 63)
    if (invoice.customer.email) doc.text(`Email: ${invoice.customer.email}`, 10, 68)
    if (invoice.customer.phone) doc.text(`Phone: ${invoice.customer.phone}`, 10, 73)

    // Items
    let y = 85
    doc.setFontSize(10)
    doc.text('Items', 10, y)
    y += 5
    invoice.items.forEach((item, i) => {
      doc.text(`${i + 1}. ${item.name}`, 12, y)
      doc.text(`x${item.quantity}`, 90, y)
      doc.text(formatCurrency(item.price * item.quantity), 125, y, { align: 'right' })
      y += 6
    })

    // Totals
    y += 6
    doc.line(10, y, 140, y)
    y += 6
    doc.text(`Subtotal: ${formatCurrency(invoice.subtotal)}`, 90, y)
    y += 5
    doc.text(`Tax: ${formatCurrency(invoice.tax)}`, 90, y)
    y += 5
    doc.setFont(undefined, 'bold')
    doc.text(`Total: ${formatCurrency(invoice.total)}`, 90, y)
    doc.setFont(undefined, 'normal')

    // "PAID" watermark
    doc.setTextColor(220, 20, 60)
    doc.setFontSize(30)
    doc.text('PAID', 75, 130, { align: 'center', angle: 25 })
    doc.setTextColor(0, 0, 0)

    // Footer
    doc.setFontSize(8)
    doc.text('Thank you for your purchase!', 75, 145, { align: 'center' })
    doc.text('Generated by Conpay Invoice System', 75, 150, { align: 'center' })

    // Save file
    doc.save(`${invoice.invoiceNumber}.pdf`)
  }
}

const deleteInvoice = async (invoiceNumber) => {
  if (confirm(`Are you sure you want to delete invoice ${invoiceNumber}?`)) {
    await invoiceStore.deleteInvoice(invoiceNumber)
  }
}
</script>

<style scoped>
.invoice-list-container {
  margin-top: 3rem;
}

.invoice-list-container h2 {
  font-size: 1.8rem;
  color: #1a202c;
  margin-bottom: 1.5rem;
}

.loading {
  text-align: center;
  padding: 3rem;
  color: #718096;
}

.empty-state {
  text-align: center;
  padding: 4rem 2rem;
  color: #718096;
}

.empty-icon {
  color: #cbd5e0;
  margin-bottom: 1rem;
}

.empty-state p {
  margin: 0.5rem 0;
  font-size: 1.2rem;
}

.empty-subtext {
  font-size: 1rem;
  color: #a0aec0;
}

.invoices-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
  gap: 1.5rem;
}

.invoice-card {
  background: white;
  border-radius: 12px;
  padding: 1.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  transition:
    transform 0.2s,
    box-shadow 0.2s;
}

.invoice-card:hover {
  transform: translateY(-4px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.invoice-card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 1rem;
  padding-bottom: 1rem;
  border-bottom: 2px solid #e2e8f0;
}

.invoice-card-header h3 {
  color: #667eea;
  margin: 0;
  font-size: 1.1rem;
}

.invoice-date {
  color: #718096;
  font-size: 0.9rem;
}

.invoice-card-body {
  margin-bottom: 1rem;
}

.customer-name {
  font-weight: 600;
  color: #1a202c;
  margin: 0 0 0.5rem 0;
}

.invoice-total {
  font-size: 1.5rem;
  font-weight: 700;
  color: #667eea;
  margin: 0.5rem 0;
}

.items-count {
  color: #718096;
  font-size: 0.9rem;
  margin: 0;
}

.invoice-card-actions {
  display: flex;
  gap: 0.5rem;
}

.btn-view {
  flex: 1;
  background: #667eea;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  cursor: pointer;
  font-weight: 500;
}

.btn-view:hover {
  background: #5a67d8;
}

.btn-download-small,
.btn-delete {
  background: #e2e8f0;
  border: none;
  padding: 0.5rem;
  border-radius: 6px;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
}

.btn-download-small:hover {
  background: #cbd5e0;
}

.btn-delete {
  background: #fed7d7;
}

.btn-delete:hover {
  background: #fc8181;
  color: white;
}
</style>
